### ISSUE TITLE
Unable to start `mongo-viewer` in Mac

### ISSUE THREAD

**Issue by vinaybedre** [marcdelalonde/mongo-viewer#3]
As soon I run `mongo-viewer` I am getting the following error
```
➜  ~ mongo-viewer
Mongo-Viewer app is started and listening on port 8080
/Users/vinay/.fnm/node-versions/v12.22.7/installation/lib/node_modules/mongo-viewer/node_modules/mongoskin/lib/utils.js:33
  var skinClassName = 'Skin' + NativeClass.name;
                                           ^

TypeError: Cannot read property 'name' of undefined
    at makeSkinClass (/Users/vinay/.fnm/node-versions/v12.22.7/installation/lib/node_modules/mongo-viewer/node_modules/mongoskin/lib/utils.js:33:44)
    at Object.<anonymous> (/Users/vinay/.fnm/node-versions/v12.22.7/installation/lib/node_modules/mongo-viewer/node_modules/mongoskin/lib/grid.js:6:35)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/vinay/.fnm/node-versions/v12.22.7/installation/lib/node_modules/mongo-viewer/node_modules/mongoskin/lib/db.js:22:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

I am running Mac M1 with 
```
➜  ~ node -v
v12.22.7

➜  ~ npm -v
6.14.15
```

**Comment by marcdelalonde** [comment]
Hey @vinaybedre,

Thank you for the feedback!

This project is no longer maintained, however I am launching soon a SaaS product (with a free tier) that give you the ability to explore all your data from your MongoDB, MySQL & PostgreSQL databases.

If it sound good to you, don't hesitate to signup to the beta, I am opening soon 🎉

[https://adminmate.io](https://adminmate.io)

Cheers ✌️

**Comment by vinaybedre** [comment]
@marcdelalonde Thanks for the invite. Joined and waiting for a link to join adminmate.
